# fly.toml app configuration file generated for nutrily-be on 2023-12-20T10:59:05+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nutrily-be"
primary_region = "waw"

[deploy]
  release_command = "prisma:dev:deploy"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
